### ISSUE TITLE
Similar vision

### ISSUE THREAD

**Issue by yyou1996** [ChandlerBang/SelfTask-GNN#1]
Hi @ChandlerBang,

Thank you for your good job. I think we have a similar vision on SS on GNN and I would like to recommend our accepted work highly related with this paper:
[When Does Self-Supervision Help Graph Convolutional Networks?](https://arxiv.org/abs/2006.09136)

Looking forward for further discussion with you on this potential direction.

**Comment by ChandlerBang** [comment]
Great!  I will read it later.  We are still improving the paper and will discuss your work in the revision : )
