### ISSUE TITLE
ica module version

### ISSUE THREAD

**Issue by wangzeyu135798** [ChandlerBang/SelfTask-GNN#3]
Hi:
   I want to learn you ica module used in this project. In src/distance.py line 8 and line 9 ,from ica.utils import ....，there is always error for me.

**Comment by wangzeyu135798** [comment]
In ica.utils, there is no load_data, pick_aggregation, create_map, build_graph etc module

**Comment by ChandlerBang** [comment]
Hi, have you tried the following commands?
```
pip uninstall ica # in case you have installed it before
git clone https://github.com/ChandlerBang/ica.git 
cd ica
python setup.py install
```

**Comment by wangzeyu135798** [comment]
Yes. I can run the code normally after trying ica comments.
Thanks!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChandlerBang/SelfTask-GNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 晚上10:14
收件人:&nbsp;"ChandlerBang/SelfTask-GNN"<SelfTask-GNN@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ChandlerBang/SelfTask-GNN] ica module version (#3)





 
Hi, have you tried the following commands?
 pip uninstall ica # in case you have installed it before git clone https://github.com/ChandlerBang/ica.git  cd ica python setup.py install

**Comment by wangzeyu135798** [comment]
Hi：
&nbsp; &nbsp;I see in your code train.py for parameter args.ssl, there are many options for different pre-training attributes in paper. I don't see finetune function in code while it appears in your paper. Are you finetune the pre-trained models for different attributes seperately?&nbsp;&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChandlerBang/SelfTask-GNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 晚上10:14
收件人:&nbsp;"ChandlerBang/SelfTask-GNN"<SelfTask-GNN@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ChandlerBang/SelfTask-GNN] ica module version (#3)





 
Hi, have you tried the following commands?
 pip uninstall ica # in case you have installed it before git clone https://github.com/ChandlerBang/ica.git  cd ica python setup.py install

**Comment by ChandlerBang** [comment]
Hi,

Actually I deleted some code to make it more neat when I uploaded my code to Github... 

Anyway, the code of finetuning is easy to write: just save the model parameters and then load the saved parameters to finetune.
